spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Wipe DB every time we start the application
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.web.error.include-message=always